### ISSUE TITLE
Docker/Deployment

### ISSUE THREAD

**Issue by dehlen** [ZackMurry/chessrs#1]
Hey,

i wanted to try this project out for my personal opening studies and wondered whether a docker-compose.yml already exists or some kind of deployment instructions?

Thanks for sharing your work open source!

Kind regards,
David

**Comment by ZackMurry** [comment]
Hi, thanks for showing interest in this project! I've just added a way to deploy it with Docker. Instructions are in the README :)

**Comment by dehlen** [comment]
Thats great. Thank you so much.
